# Python, NumPy and Vectorization
A brief introduction to some of the scientific computing used in this course. In particular the NumPy scientific computing package and its use with python.

In [68]:
import numpy as np    # it is an unofficial standard to use np for numpy
import time

<a name="toc_40015_2"></a>
# Python and NumPy <a name='Python and NumPy'></a>
Python is the programming language we will be using in this course. It has a set of numeric data types and arithmetic operations. NumPy is a library that extends the base capabilities of python to add a richer data set including more numeric types, vectors, matrices, and many matrix functions. NumPy and python  work together fairly seamlessly. Python arithmetic operators work on NumPy data types and many NumPy functions will accept python data types.


<a name="toc_40015_3"></a>
# Vectors
<a name="toc_40015_3.1"></a>
## Abstract
<img align="right" src="./images/C1_W2_Lab04_Vectors.PNG" style="width:340px;" >Vectors, as you will use them in this course, are ordered arrays of numbers. In notation, vectors are denoted with lower case bold letters such as $\mathbf{x}$.  The elements of a vector are all the same type. A vector does not, for example, contain both characters and numbers. The number of elements in the array is often referred to as the *dimension* though mathematicians may prefer *rank*. The vector shown has a dimension of $n$. The elements of a vector can be referenced with an index. In math settings, indexes typically run from 1 to n. In computer science and these labs, indexing will typically run from 0 to n-1.  In notation, elements of a vector, when referenced individually will indicate the index in a subscript, for example, the $0^{th}$ element, of the vector $\mathbf{x}$ is $x_0$. Note, the x is not bold in this case.  


<a name="toc_40015_3.2"></a>
## NumPy Arrays

NumPy's basic data structure is an indexable, n-dimensional *array* containing elements of the same type (`dtype`). Right away, you may notice we have overloaded the term 'dimension'. Above, it was the number of elements in the vector, here, dimension refers to the number of indexes of an array. A one-dimensional or 1-D array has one index.

 - 1-D array, shape (n,): n elements indexed [0] through [n-1]


<a name="toc_40015_3.3"></a>
## Vector Creation


Data creation routines in NumPy will generally have a first parameter which is the shape of the object. This can either be a single value for a 1-D result or a tuple (n,m,...) specifying the shape of the result. Below are examples of creating vectors using these routines.

In [76]:
a = np.zeros(4)
print(f"np.zeros(4) : a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = np.random.random_sample(4)
print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) : a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.59016891 0.48855887 0.52727306 0.18597929], a shape = (4,), a data type = float64


Some data creation routines do not take a shape tuple:

In [79]:
a = np.arange(4.)
print(f"np.arange(4.): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = np.random.rand(4)
print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.): a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.5679478  0.18458777 0.65035916 0.12787485], a shape = (4,), a data type = float64


values can be specified manually as well.

In [82]:
a = np.array([5,4,3,2])
print(f"np.array([5,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = np.array([5.,4,3,2])
print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]): a = [5 4 3 2], a shape = (4,), a data type = int32
np.random.random_sample(4): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


These have all created a one-dimensional vector  `a` with four elements. `a.shape` returns the dimensions. Here we see a.shape = `(4,)` indicating a 1-d array with 4 elements.  

<a name="toc_40015_3.4"></a>
## Operations on Vectors
Let's explore some operations using vectors.
<a name="toc_40015_3.4.1"></a>
### Indexing
Elements of vectors can be accessed via indexing and slicing. NumPy provides a very complete set of indexing and slicing capabilities. We will explore only the basics needed for the course here. Reference [Slicing and Indexing](https://NumPy.org/doc/stable/reference/arrays.indexing.html) for more details.  
**Indexing** means referring to *an element* of an array by its position within the array.  
**Slicing** means getting a *subset* of elements from an array based on their indices.  
NumPy starts indexing at zero so the 3rd element of an vector $\mathbf{a}$ is `a[2]`.

In [86]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)

print(f"a[2].shape: {a[2].shape}, {a[2]}, Accessing an element returns a scalar")

a[-1] = 9
try:
    print(f"The error message you'll see is: {a[10]}")
except Exception as e:
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: (), 2, Accessing an element returns a scalar
index 10 is out of bounds for axis 0 with size 10


<a name="toc_40015_3.4.2"></a>
### Slicing
Slicing creates an array of indices using a set of three values (`start:stop:step`). A subset of values is also valid. Its use is best explained by example:

In [89]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f"a\t\t = {a}")
print(f"a[2:7:1]\t = {a[2:7:1]}")
print(f"a[2:7:2] \t = {a[2:7:2]}")
print(f"a[3:]\t\t = {a[3:]}")
print(f"a[:3]\t\t = {a[:3]}")
print(f"a[:]\t\t = {a[:]}")

a		 = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1]	 = [2 3 4 5 6]
a[2:7:2] 	 = [2 4 6]
a[3:]		 = [3 4 5 6 7 8 9]
a[:3]		 = [0 1 2]
a[:]		 = [0 1 2 3 4 5 6 7 8 9]


<a name="toc_40015_3.4.3"></a>
### Single vector operations
There are a number of useful operations that involve operations on a single vector.

In [92]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f"a\t\t = {a}")
print(f"-a\t\t = {-a}")
print(f"np.sum(a) \t = {np.sum(a)}")
print(f"np.mean(a)\t = {np.mean(a)}")
print(f"a**2\t\t = {a**2}")

a		 = [0 1 2 3 4 5 6 7 8 9]
-a		 = [ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]
np.sum(a) 	 = 45
np.mean(a)	 = 4.5
a**2		 = [ 0  1  4  9 16 25 36 49 64 81]


<a name="toc_40015_3.4.4"></a>
### Vector Vector element-wise operations
Most of the NumPy arithmetic, logical and comparison operations apply to vectors as well. These operators work on an element-by-element basis. For example
$$ \mathbf{a} + \mathbf{b} = \sum_{i=0}^{n-1} a_i + b_i $$

In [95]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = a // 2

print(f"Binary operators work element wise: {a + b}")

Binary operators work element wise: [ 0  1  3  4  6  7  9 10 12 13]


Of course, for this to work correctly, the vectors must be of the same size:

In [98]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.array([0, 1, 2, 4, 5, 6, 7, 8, 9])
try:
    print(f"Binary operators work element wise: {a + b}")
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (10,) (9,) 


<a name="toc_40015_3.4.5"></a>
### Scalar Vector operations
Vectors can be 'scaled' by scalar values. A scalar value is just a number. The scalar multiplies all the elements of the vector.

In [101]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = 5 * a
print(f"b = 5 * a : {b}")

b = 5 * a : [ 0  5 10 15 20 25 30 35 40 45]


<a name="toc_40015_3.4.6"></a>
### Vector Vector dot product
The dot product is a mainstay of Linear Algebra and NumPy. This is an operation used extensively in this course and should be well understood. The dot product is shown below.

<img src="./images/C1_W2_Lab04_dot_notrans.gif" width=800>

The dot product multiplies the values in two vectors element-wise and then sums the result.
Vector dot product requires the dimensions of the two vectors to be the same.

Let's implement our own version of the dot product below:

**Using a for loop**, implement a function which returns the dot product of two vectors. The function to return given inputs $a$ and $b$:
$$ x = \sum_{i=0}^{n-1} a_i b_i $$
Assume both `a` and `b` are the same shape.

In [23]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = a // 2

print(f"my_dot(a, b) = {np.dot(a, b)}")

my_dot(a, b) = 130


Note, the dot product is expected to return a scalar value.

Let's try the same operations using `np.dot`.  

In [25]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = a // 2

print(f"NumPy 1-D np.dot(a, b) = {np.dot(a, b)}, np.dot(a, b).shape = {np.dot(a, b).shape}")

NumPy 1-D np.dot(a, b) = 130, np.dot(a, b).shape = ()


Above, you will note that the results for 1-D matched our implementation.

<a name="toc_40015_3.4.7"></a>
### The Need for Speed: vector vs for loop
We utilized the NumPy  library because it improves speed memory efficiency. Let's demonstrate:

In [27]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = a // 2
start = time.time()
dot = np.dot(a, b)
end = time.time()
print(f"my_dot(a, b) = {dot}")
print(f"Vectorized version duration: {end - start}")

start = time.time()
result = 0
for i in range(0, len(a)):
    result += a[i] * b[i]
end = time.time()
print(f"my_dot(a, b) = {result}")
print(f"loop version duration: {end - start}")

my_dot(a, b) = 130
Vectorized version duration: 0.0
my_dot(a, b) = 130
loop version duration: 0.0


So, vectorization provides a large speed up in this example. This is because NumPy makes better use of available data parallelism in the underlying hardware. GPU's and modern CPU's implement Single Instruction, Multiple Data (SIMD) pipelines allowing multiple operations to be issued in parallel. This is critical in Machine Learning where the data sets are often very large.

<a name="toc_40015_4"></a>
# Matrices


<a name="toc_40015_4.1"></a>
## Abstract
Matrices, are two dimensional arrays. The elements of a matrix are all of the same type. In notation, matrices are denoted with capitol, bold letter such as $\mathbf{X}$. In this and other labs, `m` is often the number of rows and `n` the number of columns. The elements of a matrix can be referenced with a two dimensional index. In math settings, numbers in the index typically run from 1 to n. In computer science and these labs, indexing will run from 0 to n-1.  
<figure>
    <center> <img src="./images/C1_W2_Lab04_Matrices.PNG"  alt='missing'  width=900><center/>
    <figcaption> Generic Matrix Notation, 1st index is row, 2nd is column </figcaption>
<figure/>

<a name="toc_40015_4.2"></a>
## NumPy Arrays

NumPy's basic data structure is an indexable, n-dimensional *array* containing elements of the same type (`dtype`). These were described earlier. Matrices have a two-dimensional (2-D) index [m,n].

2-D matrices are used to hold training data. Training data is $m$ examples by $n$ features creating an (m,n) array. Course 1 does not do operations directly on matrices but typically extracts an example as a vector and operates on that. Below you will review:
- data creation
- slicing and indexing

<a name="toc_40015_4.3"></a>
## Matrix Creation
The same functions that created 1-D vectors will create 2-D or n-D arrays. Here are some examples


Below, the shape tuple is provided to achieve a 2-D result. Notice how NumPy uses brackets to denote each dimension. Notice further than NumPy, when printing, will print one row per line.


In [37]:
a = np.zeros((1, 5))
print(f"a shape = {a.shape}, a = {a}")

a = np.zeros((2, 1))
print(f"a shape = {a.shape}, a = {a}")

a = np.zeros((1, 1))
print(f"a shape = {a.shape}, a = {a}")

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.]]


One can also manually specify data. Dimensions are specified with additional brackets matching the format in the printing above.

In [43]:
a = np.array([[5], [4], [3]])
print(f"a shape = {a.shape}, np.array: a = {a}")

a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


<a name="toc_40015_4.4"></a>
## Operations on Matrices
Let's explore some operations using matrices.

<a name="toc_40015_4.4.1"></a>
### Indexing


Matrices include a second index. The two indexes describe [row, column]. Access can either return an element or a row/column. See below:

In [47]:
a = np.array([[5,2], [4,4], [3,6]])
print(f"a shape = {a.shape}, np.array: a = {a}")

a shape = (3, 2), np.array: a = [[5 2]
 [4 4]
 [3 6]]


In [51]:
a = np.array([[5], [4], [3]])
print(f"a shape = {a.shape}, np.array: a = {a}")

print(f"a[2,0].shape: = {a[2,0].shape}, a[2,0] = = {a[2,0]},  type(a[2,0]) = {type(a[2,0])}")
print(f"a[2].shape: = {a[2].shape}, a[2,0] = = {a[2]},  type(a[2,0]) = {type(a[2])}")

a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
a[2,0].shape: = (), a[2,0] = = 3,  type(a[2,0]) = <class 'numpy.int32'>
a[2].shape: = (1,), a[2,0] = = [3],  type(a[2,0]) = <class 'numpy.ndarray'>


It is worth drawing attention to the last example. Accessing a matrix by just specifying the row will return a *1-D vector*.

**Reshape**  
The previous example used [reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) to shape the array.  
`a = np.arange(6).reshape(-1, 2) `   
This line of code first created a *1-D Vector* of six elements. It then reshaped that vector into a *2-D* array using the reshape command. This could have been written:  
`a = np.arange(6).reshape(3, 2) `  
To arrive at the same 3 row, 2 column array.
The -1 argument tells the routine to compute the number of rows given the size of the array and the number of columns.


<a name="toc_40015_4.4.2"></a>
### Slicing
Slicing creates an array of indices using a set of three values (`start:stop:step`). A subset of values is also valid. Its use is best explained by example:

In [59]:
a = np.array([[0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])
print(f"a = {a}")

print(f"a[0, 2:7:1] = {a[0, 2:7:1]}, a[0, 2:7:1].shape = {a[0, 2:7:1].shape}, a 1-D array \na[:, 2:7:1] = {a[:, 2:7:1]},  a[:, 2:7:1].shape = {a[:, 2:7:1].shape}a 2-D array \na[:,:] = {a[:,:]},  a[:,:].shape = {a[:,:].shape}") 
print(f"a[1,:] = {a[1,:]},  a[1,:].shape = {a[1,:].shape} a 1-D array")
print(f"a[1] = {a[1,:]},  a[1,:].shape = {a[1].shape} a 1-D array")

a = [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] = [2 3 4 5 6], a[0, 2:7:1].shape = (5,), a 1-D array 
a[:, 2:7:1] = [[ 2  3  4  5  6]
 [12 13 14 15 16]],  a[:, 2:7:1].shape = (2, 5)a 2-D array 
a[:,:] = [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]],  a[:,:].shape = (2, 10)
a[1,:] = [10 11 12 13 14 15 16 17 18 19],  a[1,:].shape = (10,) a 1-D array
a[1] = [10 11 12 13 14 15 16 17 18 19],  a[1,:].shape = (10,) a 1-D array


<a name="toc_40015_5.0"></a>
## Congratulations!
You mastered the features of Python and NumPy.